"""Generate the Phase 0 model-artifact inventory and mapping evidence.

The catalogue design's Phase 0 requires an inventory covering 100% of supported
artifact checksums, each with its declared label grammar, plus a report of how
far each label file resolves against the held sources. This walks the registry
inventory, verifies each supplied label file against its published checksum,
and measures resolution against the bundled IOC reference.

A regression test (`tests/test_registry_inventory.py`) asserts the committed
output still names every artifact checksum, so a registry change without a
regenerated inventory fails CI.

Usage:
    python scripts/build_species_catalogue_inventory.py --labels-dir /path/to/labels

`--labels-dir` holds label files named `<labels_sha256>.txt`. Files absent from
the directory are inventoried without resolution measurements.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from collections import defaultdict
from pathlib import Path

_BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

from app.services.model_registry_inventory import RegistryArtifact, registry_artifacts  # noqa: E402
from app.services.model_taxon_map import scientific_name_from_label  # noqa: E402
from app.services.species_provenance import load_source_manifest  # noqa: E402
from app.services.species_reference import SpeciesReference  # noqa: E402

DEFAULT_OUTPUT = _BACKEND_DIR.parent / "docs" / "reviews" / "2026-08-19-species-catalogue-phase0-inventory.md"


def _read_labels(labels_dir: Path, labels_sha256: str) -> list[str] | None:
    path = labels_dir / f"{labels_sha256}.txt"
    if not path.is_file():
        return None
    content = path.read_bytes()
    actual = hashlib.sha256(content).hexdigest()
    if actual != labels_sha256:
        raise SystemExit(f"{path} does not match its own name: digest is {actual}")
    return [line.strip() for line in content.decode("utf-8", errors="replace").splitlines() if line.strip()]


def _resolution(labels: list[str], label_format: str, reference: SpeciesReference) -> dict[str, object]:
    """How far one label file resolves against what the repository holds."""
    parsed = 0
    in_reference = 0
    unresolved: list[str] = []
    for label in labels:
        scientific = scientific_name_from_label(label, label_format=label_format)
        if scientific:
            parsed += 1
            if reference.lookup(scientific):
                in_reference += 1
            continue
        if label_format == "common_name" and reference.lookup(label):
            in_reference += 1
            continue
        unresolved.append(label)
    return {
        "labels": len(labels),
        "scientific_from_file": parsed,
        "in_reference": in_reference,
        "unresolved": unresolved,
    }


def _inventory_rows(artifacts: list[RegistryArtifact]) -> list[str]:
    lines = [
        "| Artifact | Kind | Runtime | Status | Scope | Label format | Model sha256 | Weights sha256 | Labels sha256 |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for a in artifacts:
        lines.append(
            f"| `{a.artifact_id}` | {a.artifact_kind} | {a.runtime} | {a.status} | {a.taxonomy_scope} "
            f"| `{a.label_format}` | `{a.sha256}` | {f'`{a.weights_sha256}`' if a.weights_sha256 else '—'} "
            f"| {f'`{a.labels_sha256}`' if a.labels_sha256 else '—'} |"
        )
    return lines


def _source_rows() -> list[str]:
    lines = [
        "| Source | Role | Pinned release | Licence | Redistribution | Content sha256 |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for source in load_source_manifest().values():
        digest = f"`{source.content_sha256}`" if source.content_sha256 else "pinned by release identifier"
        lines.append(
            f"| {source.name} | {source.role} | {source.version or '—'} | {source.licence} "
            f"| {source.redistribution} | {digest} |"
        )
    return lines


def generate(labels_dir: Path | None) -> str:
    artifacts = registry_artifacts()
    reference = SpeciesReference()

    lines = [
        "# Species catalogue Phase 0: artifact inventory and mapping evidence",
        "",
        "Generated by `backend/scripts/build_species_catalogue_inventory.py`; regenerate rather than edit.",
        "Label formats were verified against the published, checksum-matched label files on 2026-08-19.",
        "A regression test asserts this file still names every registry artifact checksum, so the",
        "inventory cannot silently fall behind the registry.",
        "",
        "Part of [Phase 0 of the versioned species catalogue](../plans/2026-08-12-versioned-species-catalogue-design.md);",
        "the source freeze itself is `backend/app/assets/species_sources.json`.",
        "",
        "## Pinned sources",
        "",
        *_source_rows(),
        "",
        "## Artifact inventory",
        "",
        "Every concrete artifact the registry supports, including region variants, which install and",
        "map as artifacts of their own. Retired classifiers are absent from the registry and carry no",
        "current mapping obligation. Crop detectors are inventoried and deliberately excluded from the",
        "species mapping: their classes are detector targets, not taxa.",
        "",
        *_inventory_rows(artifacts),
    ]

    if labels_dir is not None:
        by_labels: dict[str, list[RegistryArtifact]] = defaultdict(list)
        for artifact in artifacts:
            if artifact.labels_sha256 and artifact.label_format != "detector_classes":
                by_labels[artifact.labels_sha256].append(artifact)

        resolution_rows = [
            "| Label file | Used by | Format | Labels | Scientific from file | In bundled reference | Unresolved |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        unresolved_sections: list[str] = []
        for labels_sha256, users in sorted(by_labels.items()):
            labels = _read_labels(labels_dir, labels_sha256)
            if labels is None:
                resolution_rows.append(
                    f"| `{labels_sha256[:12]}…` | {', '.join(f'`{u.artifact_id}`' for u in users)} "
                    f"| `{users[0].label_format}` | — | — | — | file not supplied |"
                )
                continue
            result = _resolution(labels, users[0].label_format, reference)
            unresolved = result["unresolved"]
            assert isinstance(unresolved, list)
            resolution_rows.append(
                f"| `{labels_sha256[:12]}…` | {', '.join(f'`{u.artifact_id}`' for u in users)} "
                f"| `{users[0].label_format}` | {result['labels']} | {result['scientific_from_file']} "
                f"| {result['in_reference']} | {len(unresolved)} |"
            )
            if unresolved and users[0].label_format == "common_name":
                names = ", ".join(f"`{label}`" for label in unresolved)
                unresolved_sections += [
                    "",
                    f"### Unresolved in `{', '.join(u.artifact_id for u in users)}` ({len(unresolved)})",
                    "",
                    "Labels that resolve to no scientific name in the bundled IOC reference. Candidates for",
                    "the eBird crosswalk, `class_kind` declarations, or explicit unresolved rows in Phase 2.",
                    "",
                    names,
                ]

        lines += [
            "",
            "## Resolution against the bundled IOC reference",
            "",
            "Shared label files are measured once and attributed to every artifact using them.",
            "`Scientific from file` counts labels whose declared grammar yields a scientific name",
            "directly; `In bundled reference` counts labels resolvable against the committed",
            "`species_reference.db` (by scientific name, or by common name for common-name files).",
            "For the 10,000-class iNat21 files the gap is dominated by the 8,514 non-bird classes,",
            "which no bird list covers; those await the pinned Catalogue of Life import in Phase 1.",
            "",
            *resolution_rows,
            *unresolved_sections,
        ]

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--labels-dir", type=Path, default=None, help="directory of <labels_sha256>.txt files")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    content = generate(args.labels_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
